name: name_main
on: [push]
jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: python src/test.py
